stages:
  - deploy

variables:
  ANSIBLE_HOST_KEY_CHECKING: False
  ANSIBLE_PRIVATE_KEY_FILE: /root/.ssh/private_key
  GIT_SSH_COMMAND: "ssh -i /root/.ssh/gitlab_key -o StrictHostKeyChecking=no"

deploy:
  stage: deploy
  image: registry.gitlab.com/babidi34/ansible:alpine3.18
  cache:
    paths:
      - /root/.cache/pip
      - /ansible-venv
  before_script:
    - mkdir /root/.ssh
    - echo "$SSH_PRIVKEY_GITLAB_CI" | tr -d '\r' > /root/.ssh/private_key
    - echo "$SSH_PRIVATE_KEY_GITLAB" | tr -d '\r' > /root/.ssh/gitlab_key # use by ansible-galaxy
    - chmod -R 600 /root/.ssh
    - ansible-galaxy install -r requirements.yml
  script:
    - ansible-playbook deploy_nextcloud.yml -e "@$SECRETS_VARS"  -D
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
