stages:
  - deploy

deploy:
  stage: deploy
  image: registry.gitlab.com/babidi34/ansible:ansible-2.16.6
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "StrictHostKeyChecking no" > ~/.ssh/config
    - chmod 644 ~/.ssh/config
    - eval $(ssh-agent -s)
    - cat $SSH_PRIVATE_KEY_GITLAB | tr -d '\r' | ssh-add -
    - cp $SSH_PRIVKEY_GITLAB_CI ~/.ssh/id_gitlabci
    - chmod 600 ~/.ssh/id_gitlabci
    - cp $ANSIBLE_VARS .ansible_vars.yml
    - cp $ANSIBLE_REQUIREMENTS requirements.yml
    - ansible-galaxy install -r requirements.yml
  script:
    - ansible-playbook deploy_nextcloud.yml -i $ANSIBLE_INVENTORY -e ansible_user=gitlab-ci -e ansible_ssh_private_key_file=~/.ssh/id_gitlabci -D
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_NAME == "master"
